message-quoi: "§cFerme ta gueule fils de pute"
message-feur: "§cTu n'es pas drôle fils de pute\n §7(Anti-feur)"
annonce-kick: "§c§lANNONCE §8>> §7Un joueur vient de se faire expulser vers un stage pour gênance"


easter-egg-ban: "§cPoupou c'est une pute"
easter-egg-kick: "§cVous avez été banni !\n §7Poupou est interdit."
easter-egg-annonce: "§c§lANNONCE §8>> §7Un joueur vient de se faire bannir vers un camp pour poulet qui habite à Woippy"
